# cloudbuild.yaml para desplegar Django+Rasa en Cloud Run con Docker
# Reemplaza los valores en mayúsculas por los de tu proyecto

steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-southwest1-docker.pkg.dev/chatbot-456823/chatbot/chatbot:$SHORT_SHA', '.']

  # 2. Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-southwest1-docker.pkg.dev/chatbot-456823/chatbot/chatbot:$SHORT_SHA']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - chatbot
      - --image=europe-southwest1-docker.pkg.dev/chatbot-456823/chatbot/chatbot:$SHORT_SHA
      - --region=europe-southwest1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8000
      - --memory=1Gi

images:
  - europe-southwest1-docker.pkg.dev/chatbot-456823/chatbot/chatbot:$SHORT_SHA
