services:
  - type: web
    name: chatbot-rasa-flask
    env: docker
    plan: free
    region: frankfurt
    envVars:
      - key: DEBUG
        value: "False"
      - key: PORT
        value: 8000
      - key: RASA_PORT
        value: 5005
      - key: ACTIONS_PORT
        value: 5055
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"