services:
  - type: web
    name: django-rasa-chatbot
    env: docker
    plan: free
    region: frankfurt  # Región de Frankfurt (Europa)
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 8000
      - key: RASA_PORT
        value: 5005
      - key: ACTIONS_PORT
        value: 5055
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
        value: ".onrender.com,localhost,127.0.0.1" 