name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Permite ejecutar manualmente el workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          echo "Ejecutando pruebas (reemplazar con tus pruebas reales)"
          # pytest  # Descomentar y ajustar según tus pruebas
          
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.3
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true  # Esperar hasta que el despliegue termine
          github_token: ${{ secrets.GITHUB_TOKEN }} 